[package]
name = "backend"
version = "0.1.0"
authors = ["Mike Bush <platy@njk.onl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
serde = { version = "1", features = ["derive"] }
typed-arena = "2.0.1"
