[package]
name = "radar-search"
version = "0.1.0"
authors = ["Mike Bush <platy@njk.onl>"]
edition = "2018"

[dependencies]
geo = { version = "0.19", features = ["use-serde"] }
serde = { version = "1", features = ["derive"] }
chrono = "0.4"
